---
- hosts: example
  tasks:
    - name: test echo
      shell: echo "test11" 
    - name: copy file to dest
      copy:
        src: target/trucks.war
        dest: /usr/local/tomcat/webapps/ 
        owner: root

