---
- hosts: node
  tasks:
    - name: transfer deploy script
      copy: 
           src: deploy.sh
           dest: /root/
           owner: root
    - name: prepare environment
      shell: source /root/deploy.sh
    - name: copy package to dest
      copy:
        src: target/trucks.war
        dest: /usr/local/apache-tomcat-8.5.41/webapps/
        owner: root
